import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import { KakaoInitializer } from "@/features/share/ui/KakaoInitializer";
import { KAKAO_JS_KEY } from "@/shared/constants/kakao";
import { ScreenCaptureDetector } from "./_components/ScreanCaptureDetector";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Random Trip",
  description: "Generated by create next app",
  viewport: {
    width: 'device-width',
    initialScale: 1,
    maximumScale: 1,
    userScalable: false,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        {/* TODO: 스크린샷 감지 기능 추가 */}
        {/* <ScreenCaptureDetector /> */}
        <Script
          src={`//dapi.kakao.com/v2/maps/sdk.js?appkey=${KAKAO_JS_KEY}&autoload=false`}
          strategy="beforeInteractive"
        />
         <Script
          id="adsbygoogle-init"
          strategy="afterInteractive"
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-4867294106325031"
          crossOrigin="anonymous"
        />
        <KakaoInitializer />
      </body>
    </html>
  );
}
